version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: urlshortener
      DB_PASSWORD: password
      DB_NAME: urlshortener
      DB_PORT: 5432
      DATABASE_URL: localhost
    develop:
      watch:
        - action: rebuild
          path: .
          target: development
    volumes:
      - .:/app
      - go-modules:/go/pkg/mod
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: password
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  sqlc:
    image: sqlc/sqlc
    volumes:
      - .:/src
    working_dir: /src
    # This ensures the service exits after generating code
    command: generate
volumes:
  go-modules:
  postgres-data:
