// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID          int32
	OriginalUrl string
	ShortCode   string
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	ClickCount  pgtype.Int4
	CreatorIp   pgtype.Text
}
